spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: root
#
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: trace
